// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CdmUIClient is the client API for CdmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CdmUIClient interface {
	// ListDeviceSpecs returns a list of Compute Device(s) that can be started through the UI.
	ListDeviceSpecs(ctx context.Context, in *ListDeviceSpecsRequest, opts ...grpc.CallOption) (CdmUI_ListDeviceSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type cdmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCdmUIClient(cc grpc.ClientConnInterface) CdmUIClient {
	return &cdmUIClient{cc}
}

func (c *cdmUIClient) ListDeviceSpecs(ctx context.Context, in *ListDeviceSpecsRequest, opts ...grpc.CallOption) (CdmUI_ListDeviceSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CdmUI_ServiceDesc.Streams[0], "/v1.CdmUI/ListDeviceSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cdmUIListDeviceSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CdmUI_ListDeviceSpecsClient interface {
	Recv() (*ListDeviceSpecsResponse, error)
	grpc.ClientStream
}

type cdmUIListDeviceSpecsClient struct {
	grpc.ClientStream
}

func (x *cdmUIListDeviceSpecsClient) Recv() (*ListDeviceSpecsResponse, error) {
	m := new(ListDeviceSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cdmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CdmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdmUIServer is the server API for CdmUI service.
// All implementations must embed UnimplementedCdmUIServer
// for forward compatibility
type CdmUIServer interface {
	// ListDeviceSpecs returns a list of Compute Device(s) that can be started through the UI.
	ListDeviceSpecs(*ListDeviceSpecsRequest, CdmUI_ListDeviceSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCdmUIServer()
}

// UnimplementedCdmUIServer must be embedded to have forward compatible implementations.
type UnimplementedCdmUIServer struct {
}

func (UnimplementedCdmUIServer) ListDeviceSpecs(*ListDeviceSpecsRequest, CdmUI_ListDeviceSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDeviceSpecs not implemented")
}
func (UnimplementedCdmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCdmUIServer) mustEmbedUnimplementedCdmUIServer() {}

// UnsafeCdmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdmUIServer will
// result in compilation errors.
type UnsafeCdmUIServer interface {
	mustEmbedUnimplementedCdmUIServer()
}

func RegisterCdmUIServer(s grpc.ServiceRegistrar, srv CdmUIServer) {
	s.RegisterService(&CdmUI_ServiceDesc, srv)
}

func _CdmUI_ListDeviceSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDeviceSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CdmUIServer).ListDeviceSpecs(m, &cdmUIListDeviceSpecsServer{stream})
}

type CdmUI_ListDeviceSpecsServer interface {
	Send(*ListDeviceSpecsResponse) error
	grpc.ServerStream
}

type cdmUIListDeviceSpecsServer struct {
	grpc.ServerStream
}

func (x *cdmUIListDeviceSpecsServer) Send(m *ListDeviceSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CdmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CdmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CdmUI_ServiceDesc is the grpc.ServiceDesc for CdmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CdmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CdmUI",
	HandlerType: (*CdmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CdmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDeviceSpecs",
			Handler:       _CdmUI_ListDeviceSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdm-ui.proto",
}
